server:
  port: ${PORT:8080}

spring:
  application:
    name: sportsmedia

  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/sportsmedia;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}

  h2:
    console:
      enabled: true
      path: /h2-console

  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: ${JWT_SECRET:change-this-to-a-long-random-secret-key-min-32-chars}
    expiry-hours: 12

  admin:
    username: ${ADMIN_USER:supriyo}
    password: ${ADMIN_PASS:Admin@12345}

  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5500,http://127.0.0.1:5500,https://*.vercel.app}

# football:
#   api:
#     enabled: ${FOOTBALL_API_ENABLED:false}
#     token: ${FOOTBALL_API_TOKEN:}
#     base-url: ${FOOTBALL_API_BASE_URL:https://api.football-data.org/v4}
#     competitions: ${FOOTBALL_API_COMPETITIONS:PD,CL,PL,SA,BL1}
#     days-ahead: ${FOOTBALL_API_DAYS_AHEAD:14}
#     cron: "${FOOTBALL_API_CRON:0 */30 * * * *}"

football:
  api:
    enabled: ${FOOTBALL_API_ENABLED:true}
    token: ${FOOTBALL_API_TOKEN:cd764ca97105491188898b7126b212b5}
    base-url: ${FOOTBALL_API_BASE_URL:https://api.football-data.org/v4}
    competitions: ${FOOTBALL_API_COMPETITIONS:WC,CL,BL1,DED,BSA,PD,FL1,ELC,PPL,EC,SA,PL}
    days-ahead: ${FOOTBALL_API_DAYS_AHEAD:14}
    cron: "${FOOTBALL_API_CRON:0 */30 * * * *}"

    news:
  api:
    enabled: ${NEWS_API_ENABLED:true}
    token: ${NEWS_API_TOKEN:6e7328cae4b140eab27bfb44326b9a10}
    base-url: https://newsapi.org/v2
    query: football OR soccer OR "Premier League" OR "La Liga"